### ISSUE TITLE
Zoom a la capa

### ISSUE THREAD

**Issue by matiascd** [ign-argentina/argenmap#109]
Hay posibilidad de activar una capa se realice el zoom a la capa?

**Comment by Zalitoar** [comment]
Hola @matiascd hoy subimos un #508b395d5b6ee8139223d7782407a8974620770b que incluye esa funcionalidad, aunque todavía está en la rama develop porque no está probado extensivamente con varias configuraciones del visor.
Probablemente en la próxima versión se incluya este cambio.

**Comment by matiascd** [comment]
Muchas gracias!
