### ISSUE TITLE
Color de fondo (background)

### ISSUE THREAD

**Issue by roalcri** [ign-argentina/argenmap#110]
Me gustaria saber como se puede cambiar el color de fondo azul. Que archivo hay que editar y en que sector. Gracias

**Comment by andreazomoza** [comment]
Para la personalización del visor recomendamos utilizar la rama "develop", en la misma se encuentra el archivo "preferences.json" el cual facilita el cambio de varios estilos.

https://github.com/ign-argentina/argenmap/blob/develop/src/config/default/preferences.json 

Para tu consulta en particular sobre _"cambiar el color de fondo azul"_ deberías modificar los valores de las propiedades de "theme"

 "theme": {
    **"bodyBackground": "#37bbed",
    "headerBackground": "#37bbed",
    "menuBackground": "#37bbed",**
    "activeLayer": "#33b560",
    "textMenu":"white",
    "textMenuStyle":"text-shadow: #103847 1px 1px 15px",
    "textLegendMenu":"#dddddd",
    "textLegendMenuStyle":"text-shadow: #103847 1px 1px 15px",
    "iconBar":"#4f4f4f"
    },

**Comment by roalcri** [comment]
Hola. Baje la rama estable y estoy trabajando con ella. Pude cambiar el color de fondo.
Gracias
