### ISSUE TITLE
filtar capas

### ISSUE THREAD

**Issue by roalcri** [ign-argentina/argenmap#111]
Hay alguna forma de filtrar las capas a mostrar en el panel de la izquierda? Yo edite el archivo data.json agregando el parametreo "capas" pero no funciona:
{
      "type": "wmslayer",
      "peso": 10,
      "nombre": "Inventario Nacional de Glaciares",
      "short_abstract": "Version 1",
      "class": "",
      "seccion": "inventario-glaciares",
      "servicio": "wms",
      "version": "1.3.0",
      "host": "http://maping.glaciaresargentinos.gob.ar:8084/geoserver/glaciares",
      **"capas": "glaciares:glaciares_pais_v11,cerros_pais_v9"**
    }

Gracias

**Comment by andreazomoza** [comment]
Si, se pueden filtrar capas, con "allowed_layers"
{
      "type": "wmslayer",
      "peso": 70,
      "nombre": "Industria y servicios 2",
      "short_abstract": "Excluye capas, con 'allowed_layers' menciono cuales deben incluirse",
      "class": "",
      "seccion": "industria-servicios2",
      "servicio": "wms",
      "version": "1.3.0",
      "host": "https://wms.ign.gob.ar/geoserver/industria-servicios",
      **"allowed_layers": [ 
        "areas_de_fabricacion_y_procesamiento_AC070",
        "puntos_de_extraccion_AA010"]**
    }

En la siguiente carpeta hay varios ejemplos para editar capas.
https://github.com/ign-argentina/argenmap/blob/develop/src/docs/ejemplos_data_json/

**Comment by roalcri** [comment]
Buenisimo. Funcionó. Muchas gracias
