### ISSUE TITLE
Agregar capas de un mismo WMS duplica sección

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#118]
Si se agrega una capa, cambiando el nombre de la sección en el diálogo de cargar capas desde un servicio WMS y luego se agregan todas se duplica la sección en el menú de capas.

**Comment by yamilvernet** [comment]
Se valida el host al conectar un nuevo servicio, en caso de existir muestra un mensaje de tipo Toast al usuario notificando la existencia del servicio.
