### ISSUE TITLE
El visor de argenmap sería mas útil si permitiera incluir geoservicios http. Actualmente solo permite https

### ISSUE THREAD

**Issue by lreynoso-lab** [ign-argentina/argenmap#122]
Actualmente, en función de lo que he configurado, el visor solo permite incorporar wms o wfs cuyas url sean https y no permite http.
¿Es posible que se incorpore este nuevo requerimiento en una nueva versión?
No todas las fuentes auténticas de las IDE tienen sus geoservicios con url en https.

**Comment by roalcri** [comment]
Yo he insertado un wms en http y no me funciona con la rama develop. Si funciona con la rama master. Es verdad lo que pregunta lreynoso-lab?? Si es así, estaría bueno que se permita http.

**Comment by gvarela1981** [comment]
Hace muchos años que se recomienda que ningún sitio permita la conexión no segura http.
El encuentro de trabajo del grupo de tecnología de IDERA que se realizó el día 25/11/2021 publicó las recomendaciones técnicas para las IDE que forman parte de IDERA.

En ese documento, el punto 2.3 recomienda, bajo el titulo "Normativa CORS / https Obligatorios" para permitir la interoperabilidad.

Las buenas prácticas son configurar la seguridad en todas las IDE en lugar de permitir capas no seguras en argenmap.

**Comment by Zalitoar** [comment]
@lreynoso-lab Argenmap sólo admite WMS y WMTS, por el momento no soporta servicios WFS. 

Con respecto al bloqueo, se pueden dar dos tipos que afectan a la carga de servicios y que **son producidos por el navegador no por Argenmap**:

- Por contenido mixto
- Por CORS

**Bloqueo por contenido mixto:**

> Se produce al cargar en una página publicada por HTTPS servicios u otros contenidos / archivos desde otro origen o el mismo pero por HTTP. Es decir, por cargar en una página "segura" contenido "no seguro". El navegador impide su carga.

**Bloqueo por CORS (intercambio de recursos de origen cruzado o cross-origin resource sharing):**

> **Respuesta corta**: 
>
> No lo produce el protocolo de los servicios sino que _lo genera el navegador web_ al intentar cargar archivos desde un sitio distinto al visor.
>
> **Respuesta larga:**
>
> Este bloqueo se llama [CORS](https://developer.mozilla.org/es/docs/Web/HTTP/CORS) y lo aplican todos los navegadores web modernos, no se puede evitar y tampoco se recomienda deshabilitarlo ya que es una medida de seguridad. Bloquea todos los scripts (JavaScript por ejemplo) y otros archivos que puedan contener datos (XML, JSON, etc) como son los archivos de capacidades o capabilities de los WMS y WMTS. 
>
> Las imágenes no las bloquea por el momento pero desde que se implementó el bloqueo por CORS los navegadores han adoptado gradualmente este método de seguridad de forma cada vez más estricta, no puedo asegurar que a futuro las imágenes no sean bloqueadas.
>
> **Modos de evitar el bloqueo por CORS:**
>
> Una forma es seguir las recomendaciones hechas por el Grupo de Tecnología de IDERA citadas previamente por @gvarela1981 (Gracias por colaborar en la respuesta!). Donde se recomienda agregar el encabezado 'Access-Control-Allow-Origin' en cada servicio (responsabilidad de los mismos). Esto se configura en el servidor de origen de cada servicio.
>
> Otra forma de evitar el bloqueo es cargar los documentos "capabilities" o definiciones de los servicios (que no incluyan desde su origen el encabezado - solución del párrafo anterior) por medio de un proxy que _Argenmap no incluye_.
> Se puede usar un proxy público (hay muchos en la web pero con limitaciones) que agregue el encabezado o bien ejecutar proxy en la misma dirección web del visor sea como plugin de la aplicación o como una aplicación independiente.
>
> Se puede de forma alternativa agregar los servicios afectados por este bloqueo en el archivo `data.json` y especificar las capas que deben cargarse, de esta manera la aplicación omite el pedido del archivo de capacidades (GetCapabilities) y cada botón que aparece en el menú de capas genera el pedido _GetMap_ por su cuenta, como la respuesta son imágenes (teselas de una capa) las mismas no son bloqueadas por el navegador. Este método se usa en el visor de IDERA que permite cargar capas de servicios que no tienen el CORS "habilitado", pero no se pueden consultar los datos de las capas, ni hacer zoom a la extensión de las mismas ya que esas respuestas vienen en formato JSON y XML respectivamente.

Ejemplo de configuración de capas según el párrafo anterior:

`{

      "tab": {
        "id": "Datos",
        "searcheable": true,
        "content": "Datos"
      },
      "type": "wms",
      "peso": 10,
      "nombre": "Clima y meteorología",
      "short_abstract": "Información climática y meteorológica",
      "class": "",
      "seccion": "otros-clima",
      "servicio": "wms",
      "version": "1.3.0",
      "host": "https://geo.ambiente.gob.ar/geoserver/wms",
      "feature_info_format": "application/json",
      "allowed_layers": [
        "indicadoresyestadistica:estaciones_meteorologicas"
      ],
      "customize_layers": {
        "indicadoresyestadistica:estaciones_meteorologicas": {
          "new_title": "Estación meteorológica",
          "new_abstract": "Instalación destinada a medir y registrar regularmente diversas variables meteorológicas.",
          "new_keywords": "estación meteorológica, clima, meteorología, condiciones climáticas"
        }
      }
    }`

_La combinación de atributos "allowed_layers" y "customize_layers" permite definir de forma arbitraria las capas a cargar desde un servicio._
