### ISSUE TITLE
WMS en HTTP no funciona con la rama develop pero si en master

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#123]
Yo he insertado un wms en http y no me funciona con la rama develop. Si funciona con la rama master. Es verdad lo que pregunta lreynoso-lab?? Si es así, estaría bueno que se permita http.

_Originally posted by @roalcri in https://github.com/ign-argentina/argenmap/issues/122#issuecomment-1002250366_

**Comment by Zalitoar** [comment]
@roalcri moví tu consulta a un issue independiente dado que muy probablemente la causa del problema sea un cambio reciente en la rama develop que requiere una revisión y prueba más completa.

Para ello te pido que nos pases las URL de servicios que probaste y generaron los resultados mencionados.

**Comment by roalcri** [comment]
La URL del wms que estoy probando en la rama develop es:
http://maping.glaciaresargentinos.gob.ar:8081/geoserver/glaciares

**Comment by roalcri** [comment]
La URL del servicio wms que tengo configurada en la rama develop es:
http://maping.glaciaresargentinos.gob.ar:8081/geoserver/glaciares

Es la misma URL que tengo configurada en la rama master y funciona.
Gracias

**Comment by Zalitoar** [comment]
Already fixed
