### ISSUE TITLE
Nombre de secciones vacio produce error en loadServices

### ISSUE THREAD

**Issue by yamilvernet** [ign-argentina/argenmap#124]
Al editar un nombre de servicio en el modal **Agregar Capas** se puede guardar como vacio, lo cual produce errores luego en la indexación de los elementos que comforman las secciones del menú.

**Comment by yamilvernet** [comment]
Solucionado. Se agrega una validación y en caso de encontrarse vacio el input se guarda el valor previo.

**Comment by gvarela1981** [comment]
Que versión de Argenmap estas usando ?
En la versión que esta publicada en http://mapa.ign.gob.ar no te permite agregar una capa geojson sin ponerle nombre.

Te adjunto una captura de pantalla para ver si estamos hablando de lo mismo
En la parte inferior de la ventana modal hay un mennsaje en color rojo que no permite adjuntar una capa sin nombre
![error_capa_sin_nombre](https://user-images.githubusercontent.com/9384999/148779722-5cbedbb5-d0c3-4ffd-a4cd-f00056ea113c.png)

**Comment by yamilvernet** [comment]
Esto es en la rama Develop, especificamente en el componente loadServices que permite agregar servicios WMS para consultar y agregar sus capas

**Comment by Zalitoar** [comment]
@gvarela1981 en https://mapa.ign.gob.ar está la última versión estable (master), la última versión en desarrollo (rama develop) se puede probar en https://mapa.ign.gob.ar/beta/
