### ISSUE TITLE
Modificar colores de fondo y letras en la rama master

### ISSUE THREAD

**Issue by roalcri** [ign-argentina/argenmap#162]
Buen dia. Estoy usando la version master de Argenmap para el Inventario Nacional de Glaciares.
La duda que tengo es como puedo cambiar el color de la fuente del menú cuando se despliegan las capas. Otra duda que tengo es como modificar el color de la fuente en el menú de las capas bases y por ultimo, donde se modifican los estilos para el mapa responsive (por ejemplo un celular) ya que yo modifico el archivo argenmap-master/src/config/preferences.json y solo funciona en el mapa de una pc y no asi en el mapa del celular.
Muchas gracias

**Comment by Zalitoar** [comment]
¡Hola!

Hicimos algunos cambios de estilos (que están en master) por lo que ahora no se ven más en color azul "link" los nombres de las capas en el menú o los mapas base. Todavía tenemos pendiente hacer que eso sea configurable desde preferences.json pero supongo que a corto plazo lo haremos.

Por el momento podés "sobre escribir" los estilos agregando reglas de estilo propias en 'src/config/styles/css/main.css', esto incluye las características responsive, en las cuales también hemos hecho varias mejoras.

Ejemplo para cambiar el color de los nombres de las capas activas:

```
.name-layer > a > span {
  color: #37bbed;
}

li.active > .capa-title > .name-layer > a > span {
  color: #fafafa;
}
```

Hasta hoy la rama develop sigue teniendo cambios más recientes que master, podés probarla y ver si eso resuelve tus necesidades antes de probar adaptar los estilos en master.

Saludos!
Gonzalo
