### ISSUE TITLE
Modificar la sección "WMS IGN"

### ISSUE THREAD

**Issue by gvarela1981** [ign-argentina/argenmap#2]
Esta sección se genera desde un llamado a la función getGeoserver desde index.html línea 113.
Modificarlo para que se genere desde la línea 110, es decir, si el item del archivo menu.json tiene una propiedad capas.servicio = wms , el menú consule al geoserver instalado en capas.host el listado de capas y las agregue una por una llamando al método loadWms

**Comment by Zalitoar** [comment]
Corregido.
