### ISSUE TITLE
Herramienta de medición de distancias

### ISSUE THREAD

**Issue by daf111** [ign-argentina/argenmap#20]
@daf111 agrega herramientas de medición de distancias en el branch "plugins-basicos"

**Comment by daf111** [comment]
Al realizar una nueva medición. Cuando se finaliza y se vé la línea o el polígono medida, en el popup donde aparece la información, está en inglés. Revisando el código fuente del plugin se ve que no está aplicada la traducción.

**Comment by Zalitoar** [comment]
Subido a master en https://github.com/ign-argentina/argenmap/commit/eb490d2dc6cae18e4e05911be65d3b30e6d0e3f8
