### ISSUE TITLE
Incorrect tour's anchor popup position for process & add layer buttons

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#215]
![Screenshot_20230712-105532_Firefox.jpg](https://github.com/ign-argentina/argenmap/assets/3695043/5a53a1ea-2d79-41e3-b8c9-04c77fb267ed)

![Screenshot_20230712-105518_Firefox.jpg](https://github.com/ign-argentina/argenmap/assets/3695043/d4351cf0-1807-4e92-9358-cf33d770309f)

**Comment by GSC996** [comment]
change logo and set width
