### ISSUE TITLE
Cambiar iconos del botón de localización y mini mapa

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#22]
Ambos iconos se parecen, por lo que podría cambiarse el de localización por una mira (como la mayoría de las aplicaciones de mapas) y el del minimapa por otro símbolo.

**Comment by daf111** [comment]
Se modificó el icono de localización y se hizo que el minimapa siempre esté visible, por lo que no se ve más el icono correspondiente.
