### ISSUE TITLE
Hillshades from non-activated basemaps can be turned on

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#231]
Problem:
Now, other hillshades layers can be turned on, messing with the layer z order leaving shadows layer behind the basemap and its state will mismatch the state of its switch because it was changed before the basemap was selected.

Expected behavior:
Only the active basemap hillshades switch must be enabled.

**Comment by InMunken** [comment]
#4ecfe35 Only the active basemap have hillshades switch are be enabled.

**Comment by InMunken** [comment]
Problem:
When clicking the basemap item, the basemap reloads, so if hillshade was active it is left behind the basemap, making it not visible.

Expected behavior:
Clicking an already active basemap should not reload the basemap on top of the hillshade.
