### ISSUE TITLE
no funciona logo de referencias

### ISSUE THREAD

**Issue by roalcri** [ign-argentina/argenmap#238]
Buen dia. Antes que nada los felicito por continuar trabajando en este proyecto. Hace mas de 2 años que implemento argenmap como visor de mapas para el proyecto de Inventario Nacional de Glaciares del IANIGLA Conicet Mendoza.
Estoy trabajando en la ultima version de la rama estable y me encuentro con un problema al tratar de habilitar (true) el icono de referencias en archivo "preferences.json" linea 55. Cuando se habilita (true) el sitio se queda colgado, cuando lo deshabilito (false) el sitio funciona correcto pero obviamente no carga el png. Anteriormente no tuve nunca problemas.
Ya hice la edicion del fichero styles.js donde al final tiene que quedar:
function clickReferencias(img){
event.preventDefault();
$.fancybox.open({
//src : img,
src : 'src/config/styles/images/referencias-creditos_ING.png',
type : 'image',
closeBtn: 'true'
});
El fragmento del codigo (es igual al que vengo usando siempre) es:
"referencias": {
"show": false,
"icon": "src/config/styles/images/referencias-creditos_icono_ING.png",
"width":"25px",
"height":"31px"
},
Espero que me haya explicado bien.
Abrazo grande

**Comment by GSC996** [comment]
Buen día! Agradecemos su comentario y por continuar utilizando argenmap en su proyecto. Nos complace informar que hemos identificado y solucionado el problema que reportaba con el icono de referencias en la última versión de la rama estable. En estos momentos nos encontramos trabajando en la actualización de la interfaz y se ha descuidado esa funcionalidad.

El problema se originaba por una línea faltante en el archivo index.html que impedía la carga correcta de la imagen de referencias. La línea faltante era la siguiente:

```<img id="top-right-logo" src="src/styles/images/noimage.webp" alt="" title="">```

Para solucionar el problema, la hemos agregado al archivo index.html, y ya se encuentra disponible en la última versión de la rama master.

Esperamos esto solvente el problema, no duden en contactarnos cuando sea necesario.

Saludos, equipo ArgenMap IGN.

**Comment by roalcri** [comment]
Hola Gustavo, gusto en saludarte. Muchas gracias por resolver el problema, anduvo perfecto y me carga el icono que quiero. Lo que si no encuentro la forma de bajar el icono que yo puse de referencias para que quede al lado del de Ayuda de Uds. En la imagen adjunta 001 se observa el icono que puse (con la letra i) al lado del de Ayuda (asi es como esta en la version antigua). Ahora, estoy trabajando en la nueva version y me carga el icono (i) arriba del de Ayuda como se observa en la imagen adjunta 002. 
Estoy tratando de ver la forma para que quede al lado ya que sino me agranda el alto del encabezado y me queda muy grande. 
Saludos y gracias, 


Ing. Rodolfo Alejandro Crimi 
Profesional del Inventario Nacional de Glaciares 
IANIGLA-CONICET 

+54 261 5244263 


De: "Gustavo Silvestre Coutinho" ***@***.***> 
Para: "ign-argentina" ***@***.***> 
CC: "rcrimi" ***@***.***>, "Author" ***@***.***> 
Enviados: Martes, 28 de Mayo 2024 15:22:01 
Asunto: Re: [ign-argentina/argenmap] no funciona logo de referencias (Issue #238) 





Buen día! Agradecemos su comentario y por continuar utilizando argenmap en su proyecto. Nos complace informar que hemos identificado y solucionado el problema que reportaba con el icono de referencias en la última versión de la rama estable. En estos momentos nos encontramos trabajando en la actualización de la interfaz y se ha descuidado esa funcionalidad. 

El problema se originaba por una línea faltante en el archivo index.html que impedía la carga correcta de la imagen de referencias. La línea faltante era la siguiente: 

<img id="top-right-logo" src="src/styles/images/noimage.webp" alt="" title=""> 

Para solucionar el problema, la hemos agregado al archivo index.html, y ya se encuentra disponible en la última versión de la rama master. 

Esperamos esto solvente el problema, no duden en contactarnos cuando sea necesario. 

Saludos, equipo ArgenMap IGN.

**Comment by roalcri** [comment]
Pude solucionar el problema. Lo que paso es que en un principio solo descargue el fichero index.html y mirando el codigo completo en github vi que tambien se habia modificado el directorio src por lo tanto descargue todo y alli funciono. Evidentemente habian hecho cambios en ambos lugares y no solo el index. 
Desde ya muchas gracias, 

Ing. Rodolfo Alejandro Crimi 
Profesional del Inventario Nacional de Glaciares 
IANIGLA-CONICET 

+54 261 5244263 


De: "rcrimi" ***@***.***> 
Para: "ign-argentina" ***@***.***> 
Enviados: Miércoles, 29 de Mayo 2024 9:49:25 
Asunto: Re: [ign-argentina/argenmap] no funciona logo de referencias (Issue #238) 

Hola Gustavo, gusto en saludarte. Muchas gracias por resolver el problema, anduvo perfecto y me carga el icono que quiero. Lo que si no encuentro la forma de bajar el icono que yo puse de referencias para que quede al lado del de Ayuda de Uds. En la imagen adjunta 001 se observa el icono que puse (con la letra i) al lado del de Ayuda (asi es como esta en la version antigua). Ahora, estoy trabajando en la nueva version y me carga el icono (i) arriba del de Ayuda como se observa en la imagen adjunta 002. 
Estoy tratando de ver la forma para que quede al lado ya que sino me agranda el alto del encabezado y me queda muy grande. 
Saludos y gracias, 


Ing. Rodolfo Alejandro Crimi 
Profesional del Inventario Nacional de Glaciares 
IANIGLA-CONICET 

+54 261 5244263 


De: "Gustavo Silvestre Coutinho" ***@***.***> 
Para: "ign-argentina" ***@***.***> 
CC: "rcrimi" ***@***.***>, "Author" ***@***.***> 
Enviados: Martes, 28 de Mayo 2024 15:22:01 
Asunto: Re: [ign-argentina/argenmap] no funciona logo de referencias (Issue #238) 





Buen día! Agradecemos su comentario y por continuar utilizando argenmap en su proyecto. Nos complace informar que hemos identificado y solucionado el problema que reportaba con el icono de referencias en la última versión de la rama estable. En estos momentos nos encontramos trabajando en la actualización de la interfaz y se ha descuidado esa funcionalidad. 

El problema se originaba por una línea faltante en el archivo index.html que impedía la carga correcta de la imagen de referencias. La línea faltante era la siguiente: 

<img id="top-right-logo" src="src/styles/images/noimage.webp" alt="" title=""> 

Para solucionar el problema, la hemos agregado al archivo index.html, y ya se encuentra disponible en la última versión de la rama master. 

Esperamos esto solvente el problema, no duden en contactarnos cuando sea necesario. 

Saludos, equipo ArgenMap IGN.
