### ISSUE TITLE
Botón fullscreen no permite salir

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#48]
No permite salir de la pantalla completa desde el botón, sólo con escape.

**Comment by gvarela1981** [comment]
El problema se produce por capturar los eventos "enterFullscreen"y "exitFullscreen". Puede ser por una funcion con timeout o por alguna incompatibilidad con el minimap.

Cuando comento esos eventos el botón funciona correctamente, pero no veo ningún otro cambio ni ningún comentario que me diga que se está haciendo cuando ocurren esos eventos.

@daf111 podrías tirar 2 lineas comentando que hace esa función ? Está en las líneas 225 a 240 de /templates/ign-geoportal-basic/js/mapa.js

**Comment by daf111** [comment]
Lo que intenta hacer esa parte del código es por un problema de incompatibilidad entre los plugin minimapa y fullscreen. Lo que sucedía es que el minimapa comenzaba a ubicarse en cualquier lado del mapa cuando se utilizaba en modalidad fullscreen. Encontré que una de las formas de hacer que funcione correctamente es llamando al método miniMap._restore(), aguardar unos segundos que cargue el fullscreen y luego llamar al método minimap._minimize() para que el minimapa quede funcionando. Este código debería mejorarse para evitar esperar una cantidad de segundos, sino que habría que intentar resolver de fondo esta incompatibilidad.
