### ISSUE TITLE
Mover carpetas de templates

### ISSUE THREAD

**Issue by gvarela1981** [ign-argentina/argenmap#50]
Eliminar carpeta de template ign-geoportal-basic y renombrar carpeta de template ign-geoportal-minimal a argenmap-leaflet-minimal-tpl
Al mismo tiempo mover la carpeta img a la carpeta del template ign-geoportal

**Comment by gvarela1981** [comment]
En el template recorrer los items y llamar al metodo setLegendImg(img) con la nueva ruta de la imagen.
En entities.js en la clase items setear atributo legendImg en null
En entities.js en la clase ImpresorItemHTML no imprimir el tag <img> si el atributo legendImg es null
En functions.js modificar el funcion  showImageOnError(image) para devuelva un pixel vació en base64

**Comment by daf111** [comment]
Se ha realizado la modificación de las imagenes para leyendas, pero se ha decidido no separa aún el tamplate basico del proyecto.
