### ISSUE TITLE
Mostrar un mensaje de error por bloqueo CORS

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#56]

**Comment by yamilvernet** [comment]
Se cambia el modo de trabajar las promesas en ServiceLayers.js, el método handleRequest ahora trabaja en forma async/await, lo cuál permite capturar de forma correcta el error desde donde se instancie la clase ServiceLayers. 

Cuando se produce un error al obtener el capabilities, se agrega una comprobación del error.name. Cuando ocurre un error de tipo CORS, el nombre del error es un "TypeError", diferente de un 404 que es un "Error" por ejemplo. Es una buena aproximación pero no la mejor para lograr capturar errores por bloqueo de CORS.
