### ISSUE TITLE
Manejar advertencias de carga de contenido mixto

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#77]
El navegador informa la carga de contenido mixto en página segura incluso cuando proviene por HTTPS.

`Loading mixed (insecure) display content "https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/0/0/0.png" on a secure page`

Según la [documentación de Mozilla](https://developer.mozilla.org/es/docs/Web/Security/Mixed_content) es una advertencia informativa para ayudar a desarrolladores a identificar si se carga contenido mixto (en este caso una imagen). No es motivo de bloqueo pero queda pendiente revisar el tema más para descartar que sea un problema a futuro.

**Comment by pgarciajulia** [comment]
Adjunto routemap de Chrome:

https://blog.chromium.org/2020/02/protecting-users-from-insecure.html

**Comment by andreazomoza** [comment]
Se realizaron las modificaciones correspondientes y ya no se detectan errores de typo: Loading mixed (insecure) en las consolas de Firefox y Chrome.
